export enum FETCH_STATUS {
  LOADING = 'loading',
  IDLE = 'idle',
}

export enum CURRENCIES {
  EURO = 'EURO',
  MGA = 'MGA',
  USD = 'USD'
}

export enum UNIT {
  SPECIES = 'SPECIES'
}

export enum CATEGORIES_NAMES_VALUES {
  HANDCRAFT = "611277911f7dc100298bcd54",
  FOOD = "611364f4a53f7200290290f2",
}

export const CURRENCIES_DROP_DOWN_OPTIONS = [
  {label : CURRENCIES.EURO, value :CURRENCIES.EURO},
  {label : CURRENCIES.MGA, value :CURRENCIES.MGA},
  {label : CURRENCIES.USD, value :CURRENCIES.USD}
]

export const UNIT_DROP_DOWN_OPTIONS = [ 
  {label : UNIT.SPECIES, value :UNIT.SPECIES},
] 

export const CATEGORIES_DROP_DOWN_OPTIONS = [
  { label: CATEGORIES_NAMES_VALUES.HANDCRAFT, value: CATEGORIES_NAMES_VALUES.HANDCRAFT },
  { label: CATEGORIES_NAMES_VALUES.FOOD, value: CATEGORIES_NAMES_VALUES.FOOD },

]