version: "2"
services:
  mongo:
    container_name: graphqlmongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo
  app:
    container_name: graphqlapp
    image: localhost:5000/yourimage
    build: .
    ports:
      - "4000:4000"
    environment:
      - USER_UPLOAD_DIR=/images
      - USER_UPLOADED_DIR=/app/images
      - DUMMY_IMG=dummy.jpg
      - CHOKIDAR_USEPOLLING=true
    links:
      - mongo
    volumes:
      - .:/usr/src/app:consistent
      - ./uploads:/app/images:consistent
